### ISSUE TITLE
Why JWT secret key is in frontend src? 

### ISSUE THREAD

**Issue by shiyuangu** [PacktPublishing/React-17-Design-Patterns-and-Best-Practices-Third-Edition#2]
Hi Author, 
    The secret for JWT token is in the [frontend src](https://github.com/PacktPublishing/React-17-Design-Patterns-and-Best-Practices-Third-Edition/blob/main/Chapter05/graphql/frontend/src/config/common.json). But the frontend src will be delivered to the browser and hence the secret is available to the public.   What do I miss here?

**Comment by Cirych** [comment]
Hello!

As I can see, the server is starting with `"start": "ts-node src/server",` command in package.json.

And no variables will be delivered from the server side, in according to `https://github.com/PacktPublishing/React-17-Design-Patterns-and-Best-Practices-Third-Edition/blob/main/Chapter05/graphql/frontend/src/server.ts` source code.

So, it is safe.

It looks like the author has to move `server.ts` from `frontend` folder to another place.
